name: Build and Push Docker Image
on:
  workflow_dispatch:  # Allows this workflow to be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get branch name and commit SHA
        run: |
          # extract commmit number 
          COMMIT_SHORT=${GITHUB_SHA:0:7}
          echo "Commit shortened-sha: $COMMIT_SHORT"
          echo "commit_short=$COMMIT_SHORT" >> $GITHUB_ENV

          # extract branch name
          BRANCH_NAME=${GITHUB_REF##*/}
          echo "Branch name: $BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t kahshiu/k-node-express:${{ env.branch_name }}-${{ env.commit_short}}

      - name: Push Docker image
        run: docker push kahshiu/k-node-express:${{ env.branch_name }}-${{ env.commit_short}}