name: Build and Push Docker Image
on:
  # Allows this workflow to be triggered manually
  workflow_dispatch:  
    inputs:
      environment:
      branch_name:
        description: 'branch name'
        required: false
        default: 'main'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch_name }}

      - name: Get branch name and commit SHA
        run: |
          # extract commmit number 
          COMMIT_SHORT=${GITHUB_SHA:0:7}
          echo "Commit shortened-sha: $COMMIT_SHORT"
          echo "commit_short=$COMMIT_SHORT" >> $GITHUB_ENV

          # extract branch name
          BRANCH_NAME=${GITHUB_REF##*/}
          echo "Branch name: $BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Check for tag
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            VERSION_TAG=$(git describe --tags --exact-match HEAD 2>/dev/null || echo "")
            if [ -z "$VERSION_TAG" ]; then
              echo "Tag check: main branch not versioned"
              VERSION_TAG=""
            else
              echo "Tag check: main branch version found - $VERSION_TAG"
            fi
          else
            echo "Tag check: not main branch"
            VERSION_TAG=""
          fi
          echo "version_tag=${VERSION_TAG}" >> $GITHUB_ENV

      ## - name: Log in to Docker Hub
      ##   uses: docker/login-action@v2
      ##   with:
      ##     username: ${{ secrets.DOCKER_USERNAME }}
      ##     password: ${{ secrets.DOCKER_PASSWORD }}

      ## - name: Build and push Docker image
      ##   run: |
      ##     if [ -n "${{ env.version_tag }}" ]; then
      ##       echo "Building Docker ${{ env.version_tag }}"
      ##       docker build . -t kahshiu/k-node-express:${{ env.version_tag }}
      ##       docker push kahshiu/k-node-express:${{ env.version_tag }}
      ##     else
      ##       echo "Building Docker ${{ env.branch_name }}-${{ env.commit_short }}"
      ##       docker build . -t kahshiu/k-node-express:${{ env.branch_name }}-${{ env.commit_short }}
      ##       docker push kahshiu/k-node-express:${{ env.branch_name }}-${{ env.commit_short }}
      ##     fi